[application]

name = "broinfo"
out_dir = "dist"
asset_dir = "public"

[web.app]

# HTML title tag content
title = "broinfo"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "org.omusubi.aki.broinfo"
publisher = "aki.akaguma"

icon = [
  # "icons/icon.ico"
  "assets/favicon.ico"
]

copyright = "iCopyright 2026 aki.akaguma"
category = "Utility"
short_description = "Browser Information"
long_description = "Browser Information"
